language: generic

addons:
  apt:
    packages:
      - aspell
      - aspell-en
      
before_install:
  - chmod +x ci/spellcheck.sh
      
script: ./ci/spellcheck.sh

branches: 
  only:
    - gh-pages 
    - /.*/
