# Site settings
title: The Rust Programming Language Blog
description: >
  Words from the Rust team
baseurl: ""
url: "http://blog.rust-lang.org"
twitter_username: rustlang
github_username:  rust-lang

# Build settings
markdown: kramdown
