# Site settings
title: The Rust Programming Language Blog
description: >
  Words from the Rust team
baseurl: ""
url: "http://blog.rust-lang.org"
logo: "http://www.rust-lang.org/logos/rust-logo-64x64-blk.png"
twitter_username: rustlang
github_username:  rust-lang

# Build settings
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["with_toc_data", "smart"]

root: http://blog.rust-lang.org
