# Site settings
title: The Rust Programming Language Blog
description: > # this means to ignore newlines until "baseurl:"
  Words from the Rust team
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rust-lang.org"
twitter_username: rustlang
github_username:  rust-lang

# Build settings
markdown: kramdown
