[package]
name = "midyear"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "midyear"
path = "main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_index = "0.2"
enum_index_derive = "0.2"
