name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v2.5.0

      - run: cargo run
      - run: cp CNAME ./site/
      - run: touch site/.nojekyll
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/master'
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
